# Generated by Django 2.2.3 on 2019-07-12 17:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backup', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='snippet',
            old_name='file_name',
            new_name='snippet_file',
        ),
    ]
