# Generated by Django 2.2.3 on 2019-07-16 08:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backup', '0003_snippet_original_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='snippet',
            name='snippet_file',
            field=models.TextField(),
        ),
    ]
