# Generated by Django 2.2.3 on 2019-07-16 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backup', '0004_auto_20190716_0845'),
    ]

    operations = [
        migrations.AddField(
            model_name='snippet',
            name='dropbox_id',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
    ]
