# Generated by Django 2.2.3 on 2019-07-16 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backup', '0005_snippet_dropbox_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='kloudless_keys',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('key', models.TextField()),
            ],
        ),
    ]
